### ISSUE TITLE
License and F-droid

### ISSUE THREAD

**Issue by hachikoharuno** [RabehX/Securify#1]
Hello, great app, just what I was looking for.

But I would like to ask you to post the license on github under which your application is distributed and, preferably, installation instructions. I saw that you posted the source code, but you need to protect it with a license so that it is not just appropriated. (GNU, GPL, MIT...)

You can also find out about publishing plans on F-droid or its other repositories like IzzyOnDroid.

Thank you.

**Comment by RabehX** [comment]
Thank you, my friend, for your kind suggestion. However, there is a small practical error, which is closing the source for one reason: not publishing the detections to the public.

I'dont know if F-Droid accept my app with closed source or not

**Comment by hachikoharuno** [comment]
Oh, I didn't look at the contents of the archive, I thought it was all source code. In this case, F-droid will of course not accept your application. My mistake, I didn't look.

For these purposes, in general, the license is indicated so that there is no misunderstanding, so I think you should write on the project page that the license is proprietary.

P.S: Could you also tell us why you want to use closed code? I think publishing it on F-droid would greatly increase its popularity and credibility of the application. I'm just wondering, do you want to protect your intellectual property or is there a good reason for this?

**Comment by RabehX** [comment]
You see the purpose of my application, right? I cannot convert it from closed source code to open source because some detection methods cannot be made public. This will cause great harm to the Android community and Root in particular.

I don't have any idea about publishing a closed source application in F-Droid, if what you say is true about the possibility of publishing an application in F-droid which is closed source with a proprietary license, then it is better that you teach me more about this topic.

**Comment by hachikoharuno** [comment]
Oh, please forgive me, I just didn't understand at first, since English is not my native language and I used a translator.

Regarding F-droid, it compiles applications on its own, which means it needs open source, but I don't know izziondroid.

Thanks for answering.
